# Generated by Django 4.0.4 on 2022-05-29 11:33
import ckeditor.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="Title")),
                ("img", models.ImageField(upload_to="", verbose_name="Photo for news")),
                ("text", ckeditor.fields.RichTextField()),
                ("date_create", models.DateTimeField(verbose_name="Create date time")),
            ],
            options={
                "verbose_name_plural": "News",
            },
        ),
    ]
