# Generated by Django 4.0.4 on 2022-06-05 16:43
import ckeditor.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="Title")),
                (
                    "short_description",
                    models.TextField(verbose_name="Short description"),
                ),
                (
                    "img",
                    models.ImageField(upload_to="news", verbose_name="Photo for news"),
                ),
                ("text", ckeditor.fields.RichTextField(verbose_name="Text")),
                ("date_create", models.DateTimeField(verbose_name="Create date time")),
            ],
            options={
                "verbose_name_plural": "News",
            },
        ),
    ]
