# Generated by Django 4.0.4 on 2022-05-29 17:01
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="text",
            field=ckeditor.fields.RichTextField(verbose_name="Text"),
        ),
    ]
