# Generated by Django 4.0.4 on 2022-05-29 18:35
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_news_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="short_description",
            field=models.TextField(default=23, verbose_name="Short description"),
            preserve_default=False,
        ),
    ]
