# Generated by Django 4.0.4 on 2022-06-13 12:23
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="technique",
            field=models.IntegerField(
                choices=[(0, "Multiple Choice"), (1, "One Choice")],
                default=0,
                verbose_name="Type of Question",
            ),
        ),
    ]
