# Generated by Django 4.0.4 on 2022-07-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='point',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='point'),
        ),
    ]
