# Generated by Django 4.0.4 on 2022-06-15 06:14
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_question_technique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, verbose_name="Name Topic")),
            ],
        ),
        migrations.AddField(
            model_name="answer",
            name="participant_response",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizzes",
            name="short_description",
            field=models.TextField(default=23, verbose_name="Short description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quizzes",
            name="topic",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="quiz.topic",
                verbose_name="Topic",
            ),
            preserve_default=False,
        ),
    ]
