# Generated by Django 4.0.4 on 2022-07-14 16:22
from django.db import migrations
from django.db import models

import quiz.manager


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_user_managers_remove_user_create_date_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", quiz.manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Username",
            ),
        ),
    ]
