# Generated by Django 4.0.4 on 2022-07-08 08:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_answer_id_alter_question_id_alter_quiz_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="img",
            field=models.ImageField(
                default=3, upload_to="question_img", verbose_name="question_img"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
