# Generated by Django 4.0.4 on 2022-07-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='total_point',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='total point'),
            preserve_default=False,
        ),
    ]
