# Generated by Django 4.0.4 on 2022-06-15 06:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_topic_answer_participant_response_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="participant_response",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
