# Generated by Django 4.0.4 on 2022-07-14 16:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_alter_user_managers_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="Is staff"),
        ),
    ]
