# Generated by Django 4.0.4 on 2022-06-15 07:01
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_answer_participant_response"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerInWriting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_writing",
                    models.CharField(max_length=255, verbose_name="Answer Text"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="answer_writing",
                        to="quiz.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer In Writing",
                "verbose_name_plural": "Answer In Writing",
                "ordering": ["id"],
            },
        ),
    ]
