# Generated by Django 4.0.4 on 2022-07-13 04:35
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_remove_user_name_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
    ]
