# Generated by Django 4.0.4 on 2022-07-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_response_total_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('select', 'select'), ('multiple', 'multiple choice'), ('multiple_own', 'multiple with own answer')], max_length=255, verbose_name='type'),
        ),
    ]
