# Generated by Django 4.0.4 on 2022-06-15 09:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_answerinwriting"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="q_img", verbose_name="Question img"
            ),
        ),
    ]
