# Generated by Django 4.0.4 on 2022-07-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('response', 'question')},
        ),
    ]
