# Generated by Django 4.0.4 on 2022-06-18 19:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_remove_quizzes_time_question_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizzes",
            name="topic",
        ),
        migrations.AddField(
            model_name="quizzes",
            name="topic",
            field=models.ManyToManyField(to="quiz.topic", verbose_name="Topic"),
        ),
    ]
