# Generated by Django 4.0.4 on 2022-07-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='is checked'),
        ),
    ]
