# Generated by Django 4.0.4 on 2022-07-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_answer_is_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='UncheckedAnswer',
            fields=[
            ],
            options={
                'verbose_name': 'unchecked answer',
                'verbose_name_plural': 'unchecked answers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz.answer',),
        ),
        migrations.CreateModel(
            name='UncheckedResponse',
            fields=[
            ],
            options={
                'verbose_name': 'unchecked response',
                'verbose_name_plural': 'unchecked responses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz.response',),
        ),
    ]
