# Generated by Django 4.0.4 on 2022-06-21 11:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_remove_quizzes_topic_quizzes_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="customer_response",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="ball",
            field=models.IntegerField(default=3, verbose_name="ball"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="time",
            field=models.TimeField(verbose_name="%M:%S"),
        ),
    ]
