# Generated by Django 4.0.4 on 2022-06-21 11:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_answer_customer_response_question_ball_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="time",
            field=models.DurationField(),
        ),
    ]
