# Generated by Django 4.0.4 on 2022-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_uncheckedanswer_uncheckedresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('single_choice', 'single choice'), ('multiple', 'multiple choice'), ('multiple_with_own', 'multiple with own answer')], max_length=255, verbose_name='type'),
        ),
    ]
