# Generated by Django 4.0.4 on 2022-06-21 12:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0011_alter_question_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="time",
            field=models.TimeField(default="00:02:00"),
        ),
    ]
