# Generated by Django 4.0.4 on 2022-07-02 08:33
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("create_date", models.DateTimeField(verbose_name="date to check")),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "quiz_title",
                    models.CharField(max_length=225, verbose_name="Quiz title"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_answers.user",
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
