# Generated by Django 4.0.4 on 2022-07-02 10:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_answers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date to check"),
        ),
    ]
