# Generated by Django 4.0.4 on 2022-06-17 08:22
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, verbose_name="Name")),
                ("surname", models.CharField(max_length=125, verbose_name="Surname")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone number"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "cv_file",
                    models.FileField(
                        upload_to="CV_file", verbose_name="Summary PartnerCV"
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date"
                    ),
                ),
                (
                    "career",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="career.career",
                        verbose_name="Vacancy",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="career.status",
                        verbose_name="Status",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PartnerCV",
        ),
    ]
