# Generated by Django 4.0.4 on 2022-05-29 11:35
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cv",
            name="date",
        ),
        migrations.AddField(
            model_name="cv",
            name="date_create",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date"
            ),
        ),
    ]
