# Generated by Django 4.0.4 on 2022-05-28 10:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0002_career_office_career_relocation_career_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="career",
            old_name="text",
            new_name="description",
        ),
        migrations.AddField(
            model_name="career",
            name="short_description",
            field=models.TextField(default=33, verbose_name="Short description"),
            preserve_default=False,
        ),
    ]
