# Generated by Django 4.0.4 on 2022-06-17 08:22
import phonenumber_field.modelfields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=300, verbose_name="Answer")),
            ],
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "social_network",
                    models.CharField(
                        blank=True,
                        max_length=125,
                        null=True,
                        verbose_name="social_network",
                    ),
                ),
                (
                    "social_network_text",
                    models.CharField(
                        blank=True,
                        max_length=125,
                        null=True,
                        verbose_name="social_network_text",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone number"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=125, verbose_name="Full Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("direction", models.CharField(max_length=125, verbose_name="Name")),
                ("question", models.CharField(max_length=300, verbose_name="question")),
                ("answer", models.CharField(max_length=300, verbose_name="Answer")),
                (
                    "countries",
                    models.CharField(max_length=225, verbose_name="countries"),
                ),
                (
                    "file_cv",
                    models.FileField(
                        upload_to="file_cv_p", verbose_name="File PartnerCV"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="PartnerCV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=125, verbose_name="Full Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("direction", models.CharField(max_length=125, verbose_name="Name")),
                ("question", models.CharField(max_length=300, verbose_name="question")),
                ("answer", models.CharField(max_length=300, verbose_name="Answer")),
                (
                    "countries",
                    models.CharField(max_length=225, verbose_name="countries"),
                ),
                (
                    "file_cv",
                    models.FileField(
                        upload_to="file_cv_p", verbose_name="File PartnerCV"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionCV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="question")),
            ],
        ),
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, verbose_name="Name")),
            ],
        ),
    ]
