# Generated by Django 4.0.4 on 2022-06-16 11:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_site", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="social_network_text",
            field=models.CharField(
                blank=True,
                max_length=125,
                null=True,
                verbose_name="social_network_text",
            ),
        ),
    ]
