# Generated by Django 4.0.4 on 2022-06-17 10:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partner_site", "0005_cvstatus_partnercv_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={
                "verbose_name": "Contact Us Status",
                "verbose_name_plural": "Contact Us Status",
            },
        ),
    ]
