# Generated by Django 4.0.4 on 2022-06-17 10:15
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partner_site", "0007_alter_answer_options_alter_contactus_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questioncv",
            options={
                "verbose_name": "Question CV Partner",
                "verbose_name_plural": "Question CV Partner",
            },
        ),
    ]
