# Generated by Django 4.0.4 on 2022-06-17 11:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partner_site", "0008_alter_questioncv_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "verbose_name": "Answer Developer",
                "verbose_name_plural": "Answer Developer",
            },
        ),
        migrations.AlterModelOptions(
            name="cvstatus",
            options={
                "verbose_name": "CV Status Developer",
                "verbose_name_plural": "CV Status Developer",
            },
        ),
        migrations.AlterModelOptions(
            name="direction",
            options={
                "verbose_name": "Direction Developer",
                "verbose_name_plural": "Direction Developer",
            },
        ),
        migrations.AlterModelOptions(
            name="partnercv",
            options={
                "verbose_name": "Developer CV",
                "verbose_name_plural": "Developer CV",
            },
        ),
        migrations.AlterModelOptions(
            name="questioncv",
            options={
                "verbose_name": "Question CV Developer",
                "verbose_name_plural": "Question CV Developer",
            },
        ),
    ]
