# Generated by Django 4.0.4 on 2022-07-07 10:31
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partner_site", "0009_alter_answer_options_alter_cvstatus_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Answer",
            new_name="PartnerAnswer",
        ),
    ]
